Server:
  port: 7550
  delayInactivity: 100
  httpport: 3000
  baseUrl: http://askpack.ask-cs.com/standby-fair/
  authKey: 7761817a-2d23-1030-802b-005056bc7e66
  wsdl: http://knrmtest.myask.me/webservices/index.php?wsdl
  requestSim: false
  melderkamerid: meldkamer
  escalationgroupid: ddc07638-92b7-1031-908d-005056bc7e66
  sense:
    apptesttpl:
      user: apptesttpl
      pass: eadeb77d8fba90b42b32b7de13e8aaa6
